"""create sessions and bookings tables

Revision ID: 5b1c20b019f5
Revises: 
Create Date: 2026-04-25 15:36:24.304596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1c20b019f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_desc', sa.String(length=500), nullable=False),
    sa.Column('long_desc', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=255), nullable=False),
    sa.Column('learn_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'LIMITED', 'SOLDOUT', 'COMINGSOON', 'CLOSED', 'RECORDED', name='session_status'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.Enum('ZOOM', 'TEAMS', 'GOOGLE_MEET', name='session_platform'), nullable=False),
    sa.Column('meeting_link', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_sessions_capacity_positive'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_sessions_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_category'), 'sessions', ['category'], unique=False)
    op.create_index(op.f('ix_sessions_code'), 'sessions', ['code'], unique=True)
    op.create_index(op.f('ix_sessions_starts_at'), 'sessions', ['starts_at'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('bookings',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('company_or_profession', sa.String(length=150), nullable=True),
    sa.Column('learning_goals', sa.Text(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('booking_reference', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'WAITLISTED', 'CANCELED', name='booking_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference'),
    sa.UniqueConstraint('session_id', 'email', name='uq_booking_session_email')
    )
    op.create_index('ix_booking_session_created', 'bookings', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bookings_email'), 'bookings', ['email'], unique=False)
    op.create_index(op.f('ix_bookings_session_id'), 'bookings', ['session_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_session_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_email'), table_name='bookings')
    op.drop_index('ix_booking_session_created', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_starts_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_code'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_category'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
